version: '2'
services:
  nginx:
    build:
      context: ./docker/nginx
    image: reactjs_nginx
    container_name: reactjs_nginx_container
    ports:
      - "3000:8080"
    volumes:
      - ./app/dist:/wwwroot:ro
  webpack:
    build:
      context: ./docker/webpack
    image: reactjs_webpack
    container_name: reactjs_webpack_container
    volumes:
      - ./app/src:/app/src:ro
      - ./app/dist:/app/dist:z
