version: '2'
services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "3000:8080"
    volumes:
      - ./app/dist:/wwwroot:ro
  node:
    build:
      context: ./docker/node
    volumes:
      - ./app/src:/app/src:ro
      - ./app/dist:/app/dist:z
